name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Make a web call with a secret key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Define the target URL
          URL="https://archbar.me/.deploy/"
          
          # Make the HTTP GET request with the secret key parameter
          curl -v -X GET "$URL?key=$DEPLOY_KEY"
